" Use VIM settings rather than vi.
set nocompatible

source ~/.dotfiles-edge/vim/plugins.vim
source ~/.dotfiles-edge/vim/setters.vim
source ~/.dotfiles-edge/vim/mappings.vim

syntax on
filetype plugin indent on
